export const GET_GIFS_REQUEST = "GET_GIFS_REQUEST";
export const GET_GIFS_SUCCESS = "GET_GIFS_SUCCESS";
export const GET_GIFS_ERROR = "GET_GIFS_ERROR";

export const SEARCH_GIFS_REQUEST = "SEARCH_GIFS_REQUEST";
export const SEARCH_GIFS_SUCCESS = "SEARCH_GIFS_SUCCESS";
export const SEARCH_GIFS_ERROR = "SEARCH_GIFS_ERROR";

export const SAVE_FAVOURITES = "SAVE_FAVOURITES";

export const DELETE_GIF_LIST = "DELETE_GIF_LIST";
